/////////////////////// note: Feed Card Data /////////////////////////////////////
const feedCardData = [
  {
    id: 1,
    postData: require("../Assets/photo.jpeg"),
    profilePicture: require("../Assets/photo.jpeg"),
    profileName: "get from server",
    postingTime: "get from server",
    postText:
      "if text content has more than 120 words (This is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is moreThis is more)",
    onHeaderDetailsContainer: () => console.log("on Header Details Container"),
    onHeaderPictureContainer: () => console.log("on Header Picture Container"),
    onMoreIconPress: () => console.log("On More Icon Press"),
    available: true,
  },
  {
    id: 2,
    postData: require("../Assets/photo.jpeg"),
    profilePicture: require("../Assets/photo.jpeg"),
    profileName: "get from server",
    postingTime: "get from server",
    postText: "If content is less than 120 words",
    onHeaderDetailsContainer: () => console.log("on Header Details Container"),
    onHeaderPictureContainer: () => console.log("on Header Picture Container"),
    onMoreIconPress: () => console.log("On More Icon Press"),
    available: true,
  },
  {
    id: 3,
    // postData: require("../assets/photo.jpeg"),
    profilePicture: require("../Assets/photo.jpeg"),
    profileName: "get from server",
    postingTime: "get from server",
    postText: "if only text is posted",
    onHeaderDetailsContainer: () => console.log("on Header Details Container"),
    onHeaderPictureContainer: () => console.log("on Header Picture Container"),
    onMoreIconPress: () => console.log("On More Icon Press"),
    available: false,
  },
  {
    id: 4,
    // postData: require("../assets/photo.jpeg"),
    profilePicture: require("../Assets/photo.jpeg"),
    profileName: "get from server",
    postingTime: "get from server",
    // postText: "this is text",
    onHeaderDetailsContainer: () => console.log("on Header Details Container"),
    onHeaderPictureContainer: () => console.log("on Header Picture Container"),
    onMoreIconPress: () => console.log("On More Icon Press"),
    available: true,
  },
  {
    id: 5,
    // postData: require("../assets/photo.jpeg"),
    profilePicture: require("../Assets/photo.jpeg"),
    profileName: "get from server",
    postingTime: "get from server",
    postText: "this is text",
    onHeaderDetailsContainer: () => console.log("on Header Details Container"),
    onHeaderPictureContainer: () => console.log("on Header Picture Container"),
    onMoreIconPress: () => console.log("On More Icon Press"),
    available: true,
  },
];

export default feedCardData;
